---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Customer Management
  labels:
    app: Customer Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customer Management
  template:
    metadata:
      labels:
        app: Customer Management
    spec:
      containers:
        - name: Customer Management
          image: username/Customer Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Recipe and Manual Management
  labels:
    app: Recipe and Manual Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Recipe and Manual Management
  template:
    metadata:
      labels:
        app: Recipe and Manual Management
    spec:
      containers:
        - name: Recipe and Manual Management
          image: username/Recipe and Manual Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery and Courier Management
  labels:
    app: Delivery and Courier Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery and Courier Management
  template:
    metadata:
      labels:
        app: Delivery and Courier Management
    spec:
      containers:
        - name: Delivery and Courier Management
          image: username/Delivery and Courier Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Payment Management
  labels:
    app: Payment Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Payment Management
  template:
    metadata:
      labels:
        app: Payment Management
    spec:
      containers:
        - name: Payment Management
          image: username/Payment Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Customer Management
  labels:
    app: Customer Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer Management


---


apiVersion: v1
kind: Service
metadata:
  name: Recipe and Manual Management
  labels:
    app: Recipe and Manual Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Recipe and Manual Management


---


apiVersion: v1
kind: Service
metadata:
  name: Delivery and Courier Management
  labels:
    app: Delivery and Courier Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Delivery and Courier Management


---


apiVersion: v1
kind: Service
metadata:
  name: Payment Management
  labels:
    app: Payment Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Payment Management

